push Code from DEV to MASTER
phamvantanh/Huffman-Encoding pull request #4
Opened 2020-06-25 06:15 UTC by phamvantanh

2020-06-27 04:53 UTC, hientuminh commented on Algorithm/huffman.java
> +class huffman
huffman -> Huffman

2020-06-27 04:53 UTC, hientuminh commented on Algorithm/huffman.java
> +
Remove the line

2020-06-27 05:02 UTC, hientuminh commented on GUI/ConnectDB.java
> +		try
```java
try {
  Class.forName("com.mysql.cj.jdbc.Driver");
  String hostname = "localhost";
  String databaseName = "huffman";
  String user = "root";
  String password = "123456";
  String url = "jdbc:mysql://"+hostname+"/"+databaseName+"?user="+user+"&password="+password; // jdbc:mysql://localhost/huffman?user=root&password=123456
  con = DriverManager.getConnection(url);
  stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
} catch (ClassNotFoundException ex) {
  System.out.print("Error: " + ex.getMessage());
} catch(SQLException se){
  System.err.print("Error: "+se.getMessage());
}
```

2020-06-27 05:04 UTC, hientuminh commented
@phamvantanh Một số quy ước đặt tên em tham khảo:

## Class and interface
- Class names should be nouns, in mixed case with the first letter of each internal word capitalised. Interfaces name should also be capitalised just like class names.
- Use whole words and must avoid acronyms and abbreviations.
```interface  Bicycle
class MountainBike implements Bicyle

interface Sport
class Football implements Sport
```
## Methods
- Methods should be verbs, in mixed case with the first letter lowercase and with the first letter of each internal word capitalised.
```
void changeGear(int newValue);
void speedUp(int increment);
void applyBrakes(int decrement);
```
## Variables
- Should not start with underscore(‘_’) or dollar sign ‘$’ characters.
- Should be mnemonic i.e, designed to indicate to the casual observer the intent of its use.
- One-character variable names should be avoided except for temporary variables.
- Common names for temporary variables are i, j, k, m, and n for integers; c, d, and e for characters.

## Constant variables
- Should be all uppercase with words separated by underscores (“_”).
- There are various constants used in predefined classes like Float, Long, String etc.

2020-06-27 05:04 UTC, hientuminh commented on Algorithm/huffman.java
> +	// Khai báo biến
Remove comment

2020-06-27 05:05 UTC, hientuminh commented on Algorithm/huffman.java
> +	public static void encode(Note root ,String str ,Map<Character, String> huffmanCode)
Nếu hàm này trựu tượng mình có thể thêm 1 comment về example result

2020-06-27 05:07 UTC, hientuminh commented on Algorithm/huffman.java
> +	public static void builddecode(String input,String mahoa)
>builddecode -> buildDecode

2020-06-27 05:09 UTC, hientuminh commented on GUI/ConnectDB.java
> +	public void selectEncode(int indexRow, String ID, String input, String output)
Tại sao tên hàm là `selectEncode` nhưng nội dụng là lại update/insert

2020-06-27 05:12 UTC, hientuminh commented on GUI/FrameEncode.java
> +/*===========================================TẠO MENU BAR=======================================*/
Function này quá dài. Em nên tách thành từng menu, cửa sổ để sau này dễ quản lý hơn

2020-06-27 05:15 UTC, hientuminh commented on GUI/FrameEncode.java
> +	private void getInfo(JTable table,DefaultTableModel mode)
> DefaultTableModel mode
Biến này không được dùng trong function

2020-06-27 05:18 UTC, hientuminh requested changes
@phamvantanh Anh có một số góp ý sau:

1. Một pull request thì nên có một tả:
- Nội dung của pull request là gì?
- tại sao pull request này được tạo ra?
- Làm thế nào để kiểm tra được pull request hoạt động đúng.

2. Một số vấn đề về coding:
- Sử dụng quá nhiều comment không cần thiết: Mình có thể comment ở đầu class. Ở function thì mình có thể comment kiểu input, output. Ở các statement thì ko nhất thiết
- Tên biến và function đặt không thống nhất: Lúc tiếng Việt, lúc tiếng Anh
- Sử dụng tab ở IDE do đó lên github bị bể font

2020-06-29 01:52 UTC, phamvantanh commented
> @phamvantanh Anh có một số góp ý sau:
> 
> 1. Một pull request thì nên có một tả:
> 
> * Nội dung của pull request là gì?
> * tại sao pull request này được tạo ra?
> * Làm thế nào để kiểm tra được pull request hoạt động đúng.
> 
> 1. Một số vấn đề về coding:
> 
> * Sử dụng quá nhiều comment không cần thiết: Mình có thể comment ở đầu class. Ở function thì mình có thể comment kiểu input, output. Ở các statement thì ko nhất thiết
> * Tên biến và function đặt không thống nhất: Lúc tiếng Việt, lúc tiếng Anh
> * Sử dụng tab ở IDE do đó lên github bị bể font

Dạ em cảm ơn ý kiến của anh, nhóm em sẽ chỉnh sửa để hoàn thiện code của mình ạ

2020-06-29 03:11 UTC, hientuminh commented
@phamvantanh oki em

2020-06-29 14:29 UTC, closed without merging